package logic

// LocationRegion maps a location to the RegionRules() key that must be
// enterable before its own Rule is even evaluated. Locations absent from
// this map (or mapped to "") have no separate entrance gate.
var LocationRegion = map[string]string{
	"Eastern Palace - Big Chest":        "Eastern Palace",
	"Eastern Palace - Big Key Chest":    "Eastern Palace",
	"Eastern Palace - Boss":             "Eastern Palace",
	"Eastern Palace - Compass Chest":    "Eastern Palace",
	"Eastern Palace - Cannonball Chest": "Eastern Palace",
	"Eastern Palace - Map Chest":        "Eastern Palace",

	"Desert Palace - Big Chest":     "Desert Palace",
	"Desert Palace - Big Key Chest": "Desert Palace",
	"Desert Palace - Compass Chest": "Desert Palace",
	"Desert Palace - Torch":         "Desert Palace",
	"Desert Palace - Map Chest":     "Desert Palace",
	"Desert Palace - Boss":          "Desert Palace",

	"Castle Tower - Dark Maze": "Castle Tower",
	"Castle Tower - Room 03":   "Castle Tower",

	"Tower of Hera - Big Key Chest": "Tower of Hera",
	"Tower of Hera - Compass Chest": "Tower of Hera",
	"Tower of Hera - Big Chest":     "Tower of Hera",
	"Tower of Hera - Boss":          "Tower of Hera",
	"Tower of Hera - Basement Cage": "Tower of Hera",
	"Tower of Hera - Map Chest":     "Tower of Hera",

	"Palace of Darkness - Shooter Room":          "Palace of Darkness",
	"Palace of Darkness - The Arena - Ledge":     "Palace of Darkness",
	"Palace of Darkness - Big Key Chest":         "Palace of Darkness",
	"Palace of Darkness - The Arena - Bridge":    "Palace of Darkness",
	"Palace of Darkness - Big Chest":             "Palace of Darkness",
	"Palace of Darkness - Compass Chest":         "Palace of Darkness",
	"Palace of Darkness - Harmless Hellway":      "Palace of Darkness",
	"Palace of Darkness - Stalfos Basement":      "Palace of Darkness",
	"Palace of Darkness - Dark Basement - Left":  "Palace of Darkness",
	"Palace of Darkness - Dark Basement - Right": "Palace of Darkness",
	"Palace of Darkness - Map Chest":             "Palace of Darkness",
	"Palace of Darkness - Dark Maze - Top":       "Palace of Darkness",
	"Palace of Darkness - Dark Maze - Bottom":    "Palace of Darkness",
	"Palace of Darkness - Boss":                  "Palace of Darkness",

	"Swamp Palace - Entrance":             "Swamp Palace",
	"Swamp Palace - Big Chest":            "Swamp Palace",
	"Swamp Palace - Big Key Chest":        "Swamp Palace",
	"Swamp Palace - Map Chest":            "Swamp Palace",
	"Swamp Palace - West Chest":           "Swamp Palace",
	"Swamp Palace - Compass Chest":        "Swamp Palace",
	"Swamp Palace - Flooded Room - Left":  "Swamp Palace",
	"Swamp Palace - Flooded Room - Right": "Swamp Palace",
	"Swamp Palace - Waterfall Room":       "Swamp Palace",
	"Swamp Palace - Boss":                 "Swamp Palace",

	"Skull Woods - Big Chest":     "Skull Woods",
	"Skull Woods - Bridge Room":   "Skull Woods",
	"Skull Woods - Boss":          "Skull Woods",
	"Skull Woods - Big Key Chest": "Skull Woods",
	"Skull Woods - Compass Chest": "Skull Woods",
	"Skull Woods - Map Chest":     "Skull Woods",
	"Skull Woods - Pot Prison":    "Skull Woods",
	"Skull Woods - Pinball Room":  "Skull Woods",

	"Ice Palace - Spike Room":    "Ice Palace",
	"Ice Palace - Big Key Chest": "Ice Palace",
	"Ice Palace - Map Chest":     "Ice Palace",
	"Ice Palace - Compass Chest": "Ice Palace",
	"Ice Palace - Iced T Room":   "Ice Palace",
	"Ice Palace - Freezor Chest": "Ice Palace",
	"Ice Palace - Big Chest":     "Ice Palace",
	"Ice Palace - Boss":          "Ice Palace",

	"Misery Mire - Big Chest":     "Misery Mire",
	"Misery Mire - Spike Chest":   "Misery Mire",
	"Misery Mire - Main Lobby":    "Misery Mire",
	"Misery Mire - Map Chest":     "Misery Mire",
	"Misery Mire - Big Key Chest": "Misery Mire",
	"Misery Mire - Compass Chest": "Misery Mire",
	"Misery Mire - Bridge Chest":  "Misery Mire",
	"Misery Mire - Boss":          "Misery Mire",

	"Turtle Rock - Chain Chomps":              "Turtle Rock",
	"Turtle Rock - Roller Room - Left":        "Turtle Rock",
	"Turtle Rock - Roller Room - Right":       "Turtle Rock",
	"Turtle Rock - Compass Chest":             "Turtle Rock",
	"Turtle Rock - Big Chest":                 "Turtle Rock",
	"Turtle Rock - Big Key Chest":             "Turtle Rock",
	"Turtle Rock - Crystaroller Room":         "Turtle Rock",
	"Turtle Rock - Eye Bridge - Bottom Left":  "Turtle Rock",
	"Turtle Rock - Eye Bridge - Bottom Right": "Turtle Rock",
	"Turtle Rock - Eye Bridge - Top Left":     "Turtle Rock",
	"Turtle Rock - Eye Bridge - Top Right":    "Turtle Rock",
	"Turtle Rock - Boss":                      "Turtle Rock",

	"Thieves' Town - Attic":         "Thieves Town",
	"Thieves' Town - Big Chest":     "Thieves Town",
	"Thieves' Town - Blind's Cell":  "Thieves Town",
	"Thieves' Town - Boss":          "Thieves Town",
	"Thieves' Town - Map Chest":     "Thieves Town",
	"Thieves' Town - Compass Chest": "Thieves Town",
	"Thieves' Town - Ambush Chest":  "Thieves Town",
	"Thieves' Town - Big Key Chest": "Thieves Town",

	"Ganon's Tower - Bob's Torch":                    "Ganons Tower",
	"Ganon's Tower - DMs Room - Top Left":            "Ganons Tower",
	"Ganon's Tower - DMs Room - Top Right":           "Ganons Tower",
	"Ganon's Tower - DMs Room - Bottom Left":         "Ganons Tower",
	"Ganon's Tower - DMs Room - Bottom Right":        "Ganons Tower",
	"Ganon's Tower - Randomizer Room - Top Left":     "Ganons Tower",
	"Ganon's Tower - Randomizer Room - Top Right":    "Ganons Tower",
	"Ganon's Tower - Randomizer Room - Bottom Left":  "Ganons Tower",
	"Ganon's Tower - Randomizer Room - Bottom Right": "Ganons Tower",
	"Ganon's Tower - Firesnake Room":                 "Ganons Tower",
	"Ganon's Tower - Map Chest":                      "Ganons Tower",
	"Ganon's Tower - Big Chest":                      "Ganons Tower",
	"Ganon's Tower - Bob's Chest":                    "Ganons Tower",
	"Ganon's Tower - Tile Room":                      "Ganons Tower",
	"Ganon's Tower - Hope Room - Left":               "Ganons Tower",
	"Ganon's Tower - Hope Room - Right":              "Ganons Tower",
	"Ganon's Tower - Compass Room - Top Left":        "Ganons Tower",
	"Ganon's Tower - Compass Room - Top Right":       "Ganons Tower",
	"Ganon's Tower - Compass Room - Bottom Left":     "Ganons Tower",
	"Ganon's Tower - Compass Room - Bottom Right":    "Ganons Tower",
	"Ganon's Tower - Big Key Chest":                  "Ganons Tower",
	"Ganon's Tower - Big Key Room - Left":            "Ganons Tower",
	"Ganon's Tower - Big Key Room - Right":           "Ganons Tower",
	"Ganon's Tower - Mini Helmasaur Room - Left":     "Ganons Tower",
	"Ganon's Tower - Mini Helmasaur Room - Right":    "Ganons Tower",
	"Ganon's Tower - Pre-Moldorm Chest":              "Ganons Tower",
	"Ganon's Tower - Moldorm Chest":                  "Ganons Tower",

	"Mire Shed - Left":  "Mire",
	"Mire Shed - Right": "Mire",

	"Old Man":                        "West Death Mountain",
	"Ether Tablet":                   "West Death Mountain",
	"Spectacle Rock":                 "West Death Mountain",
	"Spectacle Rock Cave":            "West Death Mountain",
	"Mimic Cave":                     "East Death Mountain",
	"Floating Island":                "East Death Mountain",
	"Spiral Cave":                    "East Death Mountain",
	"Paradox Cave Lower - Far Left":  "East Death Mountain",
	"Paradox Cave Lower - Left":      "East Death Mountain",
	"Paradox Cave Lower - Right":     "East Death Mountain",
	"Paradox Cave Lower - Far Right": "East Death Mountain",
	"Paradox Cave Lower - Middle":    "East Death Mountain",
	"Paradox Cave Upper - Left":      "East Death Mountain",
	"Paradox Cave Upper - Right":     "East Death Mountain",
	"Spike Cave":                     "West Dark World Death Mountain",
	"Superbunny Cave - Top":          "East Dark World Death Mountain",
	"Superbunny Cave - Bottom":       "East Dark World Death Mountain",
	"Hookshot Cave - Top Right":      "East Dark World Death Mountain",
	"Hookshot Cave - Top Left":       "East Dark World Death Mountain",
	"Hookshot Cave - Bottom Left":    "East Dark World Death Mountain",
	"Hookshot Cave - Bottom Right":   "East Dark World Death Mountain",

	"Master Sword Pedestal":       "North West Light World",
	"King's Tomb":                 "North West Light World",
	"Pegasus Rocks":               "North West Light World",
	"Magic Bat":                   "North West Light World",
	"Sick Kid":                    "North West Light World",
	"Lumberjack Tree":             "North West Light World",
	"Graveyard Ledge":             "North West Light World",
	"Kakariko Tavern":             "North West Light World",
	"Chicken House":               "North West Light World",
	"Kakariko Well - Top":         "North West Light World",
	"Kakariko Well - Left":        "North West Light World",
	"Kakariko Well - Middle":      "North West Light World",
	"Kakariko Well - Right":       "North West Light World",
	"Kakariko Well - Bottom":      "North West Light World",
	"Blind's Hideout - Top":       "North West Light World",
	"Blind's Hideout - Left":      "North West Light World",
	"Blind's Hideout - Right":     "North West Light World",
	"Blind's Hideout - Far Left":  "North West Light World",
	"Blind's Hideout - Far Right": "North West Light World",
	"Bottle Merchant":             "North West Light World",
	"Lost Woods Hideout":          "North West Light World",
	"Mushroom":                    "North West Light World",

	"Sahasrahla":                "North East Light World",
	"King Zora":                 "North East Light World",
	"Potion Shop":               "North East Light World",
	"Zora's Ledge":              "North East Light World",
	"Waterfall Fairy - Left":    "North East Light World",
	"Waterfall Fairy - Right":   "North East Light World",
	"Sahasrahla's Hut - Left":   "North East Light World",
	"Sahasrahla's Hut - Middle": "North East Light World",
	"Sahasrahla's Hut - Right":  "North East Light World",

	"Mini Moldorm Cave - Far Left":  "South Light World",
	"Mini Moldorm Cave - Left":      "South Light World",
	"Mini Moldorm Cave - Right":     "South Light World",
	"Mini Moldorm Cave - Far Right": "South Light World",
	"Mini Moldorm Cave - NPC":       "South Light World",
	"Hobo":                          "South Light World",
	"Bombos Tablet":                 "South Light World",
	"Cave 45":                       "South Light World",
	"Checkerboard Cave":             "South Light World",
	"Library":                       "South Light World",
	"Desert Ledge":                  "South Light World",
	"Lake Hylia Island":             "South Light World",
	"Flute Spot":                    "South Light World",
	"Aginah's Cave":                 "South Light World",
	"Floodgate Chest":               "South Light World",
	"Link's House":                  "South Light World",
	"Ice Rod Cave":                  "South Light World",
	"Maze Race":                     "South Light World",
	"Sunken Treasure":               "South Light World",

	"Blacksmith":     "North West Dark World",
	"Purple Chest":   "North West Dark World",
	"Brewery":        "North West Dark World",
	"C-Shaped House": "North West Dark World",
	"Chest Game":     "North West Dark World",
	"Hammer Pegs":    "North West Dark World",
	"Bumper Cave":    "North West Dark World",

	"Catfish":               "North East Dark World",
	"Pyramid":               "North East Dark World",
	"Pyramid Fairy - Left":  "North East Dark World",
	"Pyramid Fairy - Right": "North East Dark World",

	"Hype Cave - Top":          "South Dark World",
	"Hype Cave - Middle Right": "South Dark World",
	"Hype Cave - Middle Left":  "South Dark World",
	"Hype Cave - Bottom":       "South Dark World",
	"Hype Cave - NPC":          "South Dark World",
	"Stumpy":                   "South Dark World",
	"Digging Game":             "South Dark World",
}
